"""Deterministically render the Cardboard Management workspace source."""
import json
from copy import deepcopy
from pathlib import Path

APP_PATH = Path(__file__).resolve().parents[2]
WORKSPACE = APP_PATH / "cardboard_management" / "workspace" / "cardboard_management" / "cardboard_management.json"

BASE_WORKSPACE = {'charts': [{'chart_name': 'Daily Supplied Weight', 'label': 'Daily Supplied Weight'},
            {'chart_name': 'Purchases by Cardboard Type', 'label': 'Purchases by Cardboard Type'},
            {'chart_name': 'Top Suppliers', 'label': 'Top Suppliers'},
            {'chart_name': 'Supplier Outstanding', 'label': 'Supplier Outstanding'}],
 'creation': '2026-09-07 10:30:00.000000',
 'custom_blocks': [],
 'docstatus': 0,
 'doctype': 'Workspace',
 'for_user': '',
 'hide_custom': 1,
 'icon': '',
 'idx': 0,
 'is_hidden': 0,
 'label': 'Cardboard Management',
 'links': [{'dependencies': '',
            'hidden': 0,
            'is_query_report': 0,
            'label': 'Purchasing / Supplies',
            'link_count': 2,
            'link_to': 'Purchase Invoice',
            'link_type': 'DocType',
            'onboard': 0,
            'type': 'Card Break'},
           {'dependencies': '',
            'hidden': 0,
            'is_query_report': 0,
            'label': 'Cardboard Supply',
            'link_count': 0,
            'link_to': 'Cardboard Supply',
            'link_type': 'DocType',
            'onboard': 0,
            'type': 'Link'},
           {'dependencies': '',
            'hidden': 0,
            'is_query_report': 0,
            'label': 'Purchase Invoice',
            'link_count': 0,
            'link_to': 'Purchase Invoice',
            'link_type': 'DocType',
            'onboard': 0,
            'type': 'Link'},
           {'dependencies': '',
            'hidden': 0,
            'is_query_report': 0,
            'label': 'Suppliers & Payments',
            'link_count': 2,
            'link_to': 'Supplier',
            'link_type': 'DocType',
            'onboard': 0,
            'type': 'Card Break'},
           {'dependencies': '',
            'hidden': 0,
            'is_query_report': 0,
            'label': 'Supplier',
            'link_count': 0,
            'link_to': 'Supplier',
            'link_type': 'DocType',
            'onboard': 0,
            'type': 'Link'},
           {'dependencies': '',
            'hidden': 0,
            'is_query_report': 0,
            'label': 'Cardboard Supplier Payment',
            'link_count': 0,
            'link_to': 'Cardboard Supplier Payment',
            'link_type': 'DocType',
            'onboard': 0,
            'type': 'Link'},
           {'dependencies': '',
            'hidden': 0,
            'is_query_report': 0,
            'label': 'Expenses',
            'link_count': 1,
            'link_to': 'Quick Expense',
            'link_type': 'DocType',
            'onboard': 0,
            'type': 'Card Break'},
           {'dependencies': '',
            'hidden': 0,
            'is_query_report': 0,
            'label': 'Quick Expense',
            'link_count': 0,
            'link_to': 'Quick Expense',
            'link_type': 'DocType',
            'onboard': 0,
            'type': 'Link'},
           {'dependencies': '',
            'hidden': 0,
            'is_query_report': 0,
            'label': 'Inventory',
            'link_count': 3,
            'link_to': 'Item',
            'link_type': 'DocType',
            'onboard': 0,
            'type': 'Card Break'},
           {'dependencies': '',
            'hidden': 0,
            'is_query_report': 1,
            'label': 'Stock Balance',
            'link_count': 0,
            'link_to': 'Stock Balance',
            'link_type': 'Report',
            'onboard': 0,
            'type': 'Link'},
           {'dependencies': '',
            'hidden': 0,
            'is_query_report': 0,
            'label': 'Item',
            'link_count': 0,
            'link_to': 'Item',
            'link_type': 'DocType',
            'onboard': 0,
            'type': 'Link'},
           {'dependencies': '',
            'hidden': 0,
            'is_query_report': 0,
            'label': 'Warehouse',
            'link_count': 0,
            'link_to': 'Warehouse',
            'link_type': 'DocType',
            'onboard': 0,
            'type': 'Link'},
           {'dependencies': '',
            'hidden': 0,
            'is_query_report': 0,
            'label': 'Reports',
            'link_count': 3,
            'link_to': 'Stock Balance',
            'link_type': 'DocType',
            'onboard': 0,
            'type': 'Card Break'},
           {'dependencies': '',
            'hidden': 0,
            'is_query_report': 1,
            'label': 'Stock Balance',
            'link_count': 0,
            'link_to': 'Stock Balance',
            'link_type': 'Report',
            'onboard': 0,
            'type': 'Link'},
           {'dependencies': '',
            'hidden': 0,
            'is_query_report': 1,
            'label': 'Supplier Outstanding',
            'link_count': 0,
            'link_to': 'Accounts Payable',
            'link_type': 'Report',
            'onboard': 0,
            'type': 'Link'},
           {'dependencies': '',
            'hidden': 0,
            'is_query_report': 1,
            'label': 'Purchase Register',
            'link_count': 0,
            'link_to': 'Purchase Register',
            'link_type': 'Report',
            'onboard': 0,
            'type': 'Link'},
           {'dependencies': '',
            'hidden': 0,
            'is_query_report': 0,
            'label': 'Settings',
            'link_count': 1,
            'link_to': 'Cardboard Dashboard Settings',
            'link_type': 'DocType',
            'onboard': 0,
            'type': 'Card Break'},
           {'dependencies': '',
            'hidden': 0,
            'is_query_report': 0,
            'label': 'Dashboard Settings',
            'link_count': 0,
            'link_to': 'Cardboard Dashboard Settings',
            'link_type': 'DocType',
            'onboard': 0,
            'type': 'Link'}],
 'modified': '2026-09-09 14:19:32.000000',
 'modified_by': 'Administrator',
 'module': 'Cardboard Management',
 'name': 'Cardboard Management',
 'number_cards': [{'label': "Today's Supplies Weight", 'number_card_name': "Today's Supplies Weight"},
                  {'label': "Today's Purchase Amount", 'number_card_name': "Today's Purchase Amount"},
                  {'label': "Today's Supplier Payments", 'number_card_name': "Today's Supplier Payments"},
                  {'label': "Today's Expenses", 'number_card_name': "Today's Expenses"},
                  {'label': 'Current Stock Weight', 'number_card_name': 'Current Stock Weight'},
                  {'label': 'Supplier Outstanding', 'number_card_name': 'Supplier Outstanding'},
                  {'label': 'This Month Purchased Weight', 'number_card_name': 'This Month Purchased Weight'},
                  {'label': 'This Month Purchase Cost', 'number_card_name': 'This Month Purchase Cost'},
                  {'label': 'This Month Expenses', 'number_card_name': 'This Month Expenses'},
                  {'label': 'This Month Paid to Suppliers',
                   'number_card_name': 'This Month Paid to Suppliers'}],
 'owner': 'Administrator',
 'parent_page': '',
 'public': 1,
 'quick_lists': [],
 'restrict_to_domain': '',
 'roles': [{'role': 'Cardboard Operator'}],
 'sequence_id': 99.0,
 'shortcuts': [{'color': 'Blue',
                 'label': 'New Cardboard Supply',
                 'link_to': 'Cardboard Supply',
                 'type': 'DocType',
                 'doc_view': 'New'},
                {'color': 'Orange',
                 'label': 'New Supplier Payment',
                 'link_to': 'Cardboard Supplier Payment',
                 'type': 'DocType',
                 'doc_view': 'New'},
                {'color': 'Red',
                 'label': 'New Expense',
                 'link_to': 'Quick Expense',
                 'type': 'DocType',
                 'doc_view': 'New'},
                {'color': 'Green',
                 'label': 'New Supplier',
                 'link_to': 'Supplier',
                 'type': 'DocType',
                 'doc_view': 'New'},
                {'color': 'Blue',
                 'label': 'Supplies',
                 'link_to': 'Cardboard Supply',
                 'type': 'DocType',
                 'doc_view': 'List'},
                {'color': 'Green',
                 'label': 'Suppliers',
                 'link_to': 'Supplier',
                 'type': 'DocType',
                 'doc_view': 'List'},
                {'color': 'Orange',
                 'label': 'Payments',
                 'link_to': 'Cardboard Supplier Payment',
                 'type': 'DocType',
                 'doc_view': 'List'},
                {'color': 'Red',
                 'label': 'Expenses',
                 'link_to': 'Quick Expense',
                 'type': 'DocType',
                 'doc_view': 'List'},
                {'color': 'Grey', 'label': 'Inventory', 'link_to': 'Stock Balance', 'type': 'Report'},
                {'color': 'Grey', 'label': 'Reports', 'link_to': 'Accounts Payable', 'type': 'Report'},
                {'color': 'Purple',
                 'label': 'Settings',
                 'link_to': 'Cardboard Dashboard Settings',
                 'type': 'DocType'}],
 'title': 'Cardboard Management'}

CONTENT_BLOCKS = [{'id': 'cm-operational-home',
  'type': 'header',
  'data': {'text': '<span class="h4"><b>Operational Home</b></span>', 'col': 12}},
 {'id': 'cm-quick-actions',
  'type': 'header',
  'data': {'text': '<span class="h4"><b>Quick Actions</b></span>', 'col': 12}},
 {'id': 'cm-primary-shortcut-0',
  'type': 'shortcut',
  'data': {'shortcut_name': 'New Cardboard Supply', 'col': 3}},
 {'id': 'cm-primary-shortcut-1',
  'type': 'shortcut',
  'data': {'shortcut_name': 'New Supplier Payment', 'col': 3}},
 {'id': 'cm-primary-shortcut-2', 'type': 'shortcut', 'data': {'shortcut_name': 'New Expense', 'col': 3}},
 {'id': 'cm-primary-shortcut-3', 'type': 'shortcut', 'data': {'shortcut_name': 'New Supplier', 'col': 3}},
 {'id': 'cm-spacer-quick', 'type': 'spacer', 'data': {'col': 12}},
 {'id': 'cm-main-areas',
  'type': 'header',
  'data': {'text': '<span class="h4"><b>Main Work Areas</b></span>', 'col': 12}},
 {'id': 'cm-navigation-shortcut-0', 'type': 'shortcut', 'data': {'shortcut_name': 'Supplies', 'col': 2}},
 {'id': 'cm-navigation-shortcut-1', 'type': 'shortcut', 'data': {'shortcut_name': 'Suppliers', 'col': 2}},
 {'id': 'cm-navigation-shortcut-2', 'type': 'shortcut', 'data': {'shortcut_name': 'Payments', 'col': 2}},
 {'id': 'cm-navigation-shortcut-3', 'type': 'shortcut', 'data': {'shortcut_name': 'Expenses', 'col': 2}},
 {'id': 'cm-navigation-shortcut-4', 'type': 'shortcut', 'data': {'shortcut_name': 'Inventory', 'col': 2}},
 {'id': 'cm-navigation-shortcut-5', 'type': 'shortcut', 'data': {'shortcut_name': 'Reports', 'col': 2}},
 {'id': 'cm-spacer-navigation', 'type': 'spacer', 'data': {'col': 12}},
 {'id': 'cm-today', 'type': 'header', 'data': {'text': '<span class="h4"><b>TODAY</b></span>', 'col': 12}},
 {'id': 'cm-today-card-0',
  'type': 'number_card',
  'data': {'number_card_name': "Today's Supplies Weight", 'col': 3}},
 {'id': 'cm-today-card-1',
  'type': 'number_card',
  'data': {'number_card_name': "Today's Purchase Amount", 'col': 3}},
 {'id': 'cm-today-card-2',
  'type': 'number_card',
  'data': {'number_card_name': "Today's Supplier Payments", 'col': 3}},
 {'id': 'cm-today-card-3', 'type': 'number_card', 'data': {'number_card_name': "Today's Expenses", 'col': 3}},
 {'id': 'cm-spacer-today', 'type': 'spacer', 'data': {'col': 12}},
 {'id': 'cm-current',
  'type': 'header',
  'data': {'text': '<span class="h4"><b>CURRENT</b></span>', 'col': 12}},
 {'id': 'cm-current-card-0',
  'type': 'number_card',
  'data': {'number_card_name': 'Current Stock Weight', 'col': 6}},
 {'id': 'cm-current-card-1',
  'type': 'number_card',
  'data': {'number_card_name': 'Supplier Outstanding', 'col': 6}},
 {'id': 'cm-spacer-current', 'type': 'spacer', 'data': {'col': 12}},
 {'id': 'cm-month',
  'type': 'header',
  'data': {'text': '<span class="h4"><b>THIS MONTH</b></span>', 'col': 12}},
 {'id': 'cm-month-card-0',
  'type': 'number_card',
  'data': {'number_card_name': 'This Month Purchased Weight', 'col': 3}},
 {'id': 'cm-month-card-1',
  'type': 'number_card',
  'data': {'number_card_name': 'This Month Purchase Cost', 'col': 3}},
 {'id': 'cm-month-card-2',
  'type': 'number_card',
  'data': {'number_card_name': 'This Month Expenses', 'col': 3}},
 {'id': 'cm-month-card-3',
  'type': 'number_card',
  'data': {'number_card_name': 'This Month Paid to Suppliers', 'col': 3}},
 {'id': 'cm-spacer-month', 'type': 'spacer', 'data': {'col': 12}},
 {'id': 'cm-charts', 'type': 'header', 'data': {'text': '<span class="h4"><b>Charts</b></span>', 'col': 12}},
 {'id': 'cm-chart-0', 'type': 'chart', 'data': {'chart_name': 'Daily Supplied Weight', 'col': 6}},
 {'id': 'cm-chart-1', 'type': 'chart', 'data': {'chart_name': 'Purchases by Cardboard Type', 'col': 6}},
 {'id': 'cm-chart-2', 'type': 'chart', 'data': {'chart_name': 'Top Suppliers', 'col': 6}},
 {'id': 'cm-chart-3', 'type': 'chart', 'data': {'chart_name': 'Supplier Outstanding', 'col': 6}},
 {'id': 'cm-spacer-charts', 'type': 'spacer', 'data': {'col': 12}},
 {'id': 'cm-more', 'type': 'header', 'data': {'text': '<span class="h4"><b>More</b></span>', 'col': 12}},
 {'id': 'cm-card-0', 'type': 'card', 'data': {'card_name': 'Purchasing / Supplies', 'col': 4}},
 {'id': 'cm-card-1', 'type': 'card', 'data': {'card_name': 'Suppliers & Payments', 'col': 4}},
 {'id': 'cm-card-2', 'type': 'card', 'data': {'card_name': 'Expenses', 'col': 4}},
 {'id': 'cm-card-3', 'type': 'card', 'data': {'card_name': 'Inventory', 'col': 4}},
 {'id': 'cm-card-4', 'type': 'card', 'data': {'card_name': 'Reports', 'col': 4}},
 {'id': 'cm-card-settings', 'type': 'card', 'data': {'card_name': 'Settings', 'col': 4}},
 {'id': 'cm-spacer-more', 'type': 'spacer', 'data': {'col': 12}},
 {'id': 'cm-coming-soon',
  'type': 'header',
  'data': {'text': '<span class="h4"><b>Coming Soon</b></span>', 'col': 12}},
 {'id': 'cm-coming-soon-text',
  'type': 'paragraph',
  'data': {'text': '<span class="text-muted">Scale Integration &mdash; Not implemented yet.</span>',
           'col': 12}}]


def build_workspace():
    workspace = deepcopy(BASE_WORKSPACE)
    workspace["content"] = json.dumps(CONTENT_BLOCKS)
    return workspace


def main():
    WORKSPACE.parent.mkdir(parents=True, exist_ok=True)
    WORKSPACE.write_text(json.dumps(build_workspace(), indent=1) + "\n", encoding="utf-8")
    print(f"wrote {WORKSPACE}")


if __name__ == "__main__":
    main()
