import frappe
from frappe import _
from frappe.model.document import Document
from frappe.utils import flt, getdate, nowdate


class CardboardSupplierPayment(Document):
	# Operational supplier payment. All accounting lives in the linked standard
	# Payment Entry generated by ERPNext; this wrapper never writes Purchase
	# Invoice outstanding amounts, Payment Ledger rows, GL entries, or supplier
	# balances itself. ERPNext stays the single ledger and balance authority.
	INTEGRATION_STATUS_DRAFT = "Not Generated"
	INTEGRATION_STATUS_SUBMITTED = "Submitted"
	INTEGRATION_STATUS_CANCELLED = "Cancelled"

	def validate(self):
		self.validate_supplier()
		self.validate_amount()
		self.validate_mode_of_payment()
		self.validate_reference()
		self.validate_open_outstanding()

	def onload(self):
		# Populate the virtual display fields (plain attributes, serialized to
		# the client; never stored - no DB columns exist for them).
		self.set_display_attributes()

	def before_cancel(self):
		# Standard ERPNext controller pattern (cf. Payment Entry / Journal Entry):
		# the forward link from this wrapper to its Payment Entry is intentional,
		# so the wrapper's own backlink must not block the native cancellation
		# order (Payment Entry cancels first, while this document keeps its link).
		self.ignore_linked_doctypes = (
			"GL Entry",
			"Payment Ledger Entry",
			"Repost Payment Ledger",
			"Repost Payment Ledger Items",
			"Repost Accounting Ledger",
			"Repost Accounting Ledger Items",
			"Unreconcile Payment",
			"Unreconcile Payment Entries",
			"Advance Payment Ledger Entry",
		)
		self.cancel_payment_entry()

	# Virtual display fields (is_virtual=1, no DB columns). Properties keep the
	# values computed from ERPNext data at all times: ERPNext remains the only
	# outstanding/balance authority and nothing snapshot-like is persisted.
	@property
	def payment_status(self):
		if self.docstatus == 2:
			return self.INTEGRATION_STATUS_CANCELLED
		if self.docstatus == 1 and self.payment_entry:
			payment_entry_docstatus = frappe.db.get_value(
				"Payment Entry", self.payment_entry, "docstatus"
			)
			if payment_entry_docstatus == 1:
				return self.INTEGRATION_STATUS_SUBMITTED
			if payment_entry_docstatus == 2:
				# The Payment Entry was cancelled outside this wrapper; the
				# wrapper stays read-only and reports Cancelled.
				return self.INTEGRATION_STATUS_CANCELLED
		return self.INTEGRATION_STATUS_DRAFT

	@payment_status.setter
	def payment_status(self, value):
		# Virtual field: keep the plain attribute in sync for client payloads.
		self.set("payment_status", value)

	@property
	def current_supplier_outstanding(self):
		if self.docstatus == 2:
			return None
		company, _amount = self._payment_summary_context()
		if not (self.supplier and company):
			return None
		return self._supplier_outstanding(self.supplier, company)

	@current_supplier_outstanding.setter
	def current_supplier_outstanding(self, value):
		self.set("current_supplier_outstanding", value)

	@property
	def expected_remaining_outstanding(self):
		if self.docstatus != 0:
			return None
		company, amount = self._payment_summary_context()
		if not (self.supplier and company):
			return None
		return max(amount - flt(self.amount or 0), 0)

	@expected_remaining_outstanding.setter
	def expected_remaining_outstanding(self, value):
		self.set("expected_remaining_outstanding", value)

	def set_display_attributes(self):
		# Plain attributes shadow nothing: the properties above compute on read,
		# so nothing to precompute; kept for explicit onload clarity.
		self.set("payment_status", self.payment_status)
		self.set("current_supplier_outstanding", self.current_supplier_outstanding)
		self.set("expected_remaining_outstanding", self.expected_remaining_outstanding)

	def _payment_summary_context(self):
		"""Return (company, current total outstanding) for the display fields."""
		company = self.company or self._resolve_company_quietly()
		if not (self.supplier and company):
			return None, None
		return company, self._supplier_outstanding(self.supplier, company)

	def validate_supplier(self):
		if not self.supplier:
			frappe.throw(_("Supplier is required"))
		if not frappe.db.exists("Supplier", self.supplier):
			frappe.throw(_("Supplier {0} does not exist").format(frappe.bold(self.supplier)))
		if frappe.db.get_value("Supplier", self.supplier, "disabled"):
			frappe.throw(_("This supplier is disabled"))

	def validate_amount(self):
		if flt(self.amount) <= 0:
			frappe.throw(_("Amount must be greater than zero"))

	def validate_mode_of_payment(self):
		if not self.mode_of_payment:
			frappe.throw(_("Mode of Payment is required"))
		if not frappe.db.exists("Mode of Payment", self.mode_of_payment):
			frappe.throw(
				_("Mode of Payment {0} does not exist").format(frappe.bold(self.mode_of_payment))
			)
		if not frappe.db.get_value("Mode of Payment", self.mode_of_payment, "enabled"):
			frappe.throw(
				_("Mode of Payment {0} is disabled").format(frappe.bold(self.mode_of_payment))
			)

	def validate_reference(self):
		if self.reference_date and not self.reference_no:
			frappe.throw(_("Reference No is required when a Reference Date is set"))

	def validate_open_outstanding(self):
		company = resolve_payment_company(self.supplier)
		self.company = self.company or company
		if not self._qualifying_invoices(self.supplier, company):
			frappe.throw(_("No outstanding invoices exist for this supplier"))

	def on_submit(self):
		self._lock_for_integration()
		existing_name = self._existing_payment_entry_name()
		if existing_name:
			self._complete_existing_payment_entry(existing_name)
		else:
			payment_entry = self._generate_payment_entry(self)
			payment_entry.insert()
			self._validate_payment_entry_mapping(payment_entry)
			payment_entry.submit()
			self._validate_payment_entry_mapping(payment_entry)
			self._set_payment_entry_link(payment_entry.name)

	def cancel_payment_entry(self):
		# A submitted wrapper owns exactly one native Payment Entry; cancelling
		# the wrapper cancels that entry so ERPNext itself restores the Purchase
		# Invoice outstanding amounts. An already-cancelled entry (external
		# cancellation) is tolerated and only recorded on the wrapper.
		linked_name = self.payment_entry or frappe.db.get_value(
			"Cardboard Supplier Payment", self.name, "payment_entry"
		)
		if not linked_name:
			frappe.throw(
				_("Cardboard Supplier Payment {0} has no linked Payment Entry").format(
					frappe.bold(self.name)
				)
			)
		payment_entry = frappe.get_doc("Payment Entry", linked_name)
		if payment_entry.docstatus == 2:
			return
		self._validate_payment_entry_mapping(payment_entry)
		if payment_entry.docstatus == 0:
			frappe.throw(
				_("Generated Payment Entry {0} must be submitted before cancelling").format(
					frappe.bold(linked_name)
				)
			)
		# The forward link from this wrapper to the Payment Entry is intentional:
		# the Payment Entry must cancel first while this document keeps its link.
		# ERPNext's Payment Entry.on_cancel overwrites ignore_linked_doctypes, so
		# the parent-driven cancellation uses Frappe's ignore_links flag instead;
		# the mapping validation above is the stricter check that replaces the
		# skipped reverse-link validation (cf. ERPNext internal cancel flows).
		payment_entry.flags.ignore_links = True
		payment_entry.ignore_linked_doctypes = ("Cardboard Supplier Payment",)
		payment_entry.cancel()

	def _lock_for_integration(self):
		# QuickExpense precedent: serialize generation per wrapper so concurrent
		# submissions cannot create duplicate Payment Entries.
		frappe.db.sql(
			"select name from `tabCardboard Supplier Payment` where name = %s for update",
			(self.name,),
		)
		self.payment_entry = frappe.db.get_value(
			"Cardboard Supplier Payment", self.name, "payment_entry"
		)

	def _existing_payment_entry_name(self):
		# QuickExpense precedent: the wrapper's own forward link is the
		# idempotency source. The per-wrapper row lock plus the single
		# transaction covering insert/submit/link-persist guarantee that a
		# committed Payment Entry always has its link, so a retry or concurrent
		# submit completes the existing entry instead of generating a duplicate.
		return self.payment_entry or frappe.db.get_value(
			"Cardboard Supplier Payment", self.name, "payment_entry"
		)

	def _complete_existing_payment_entry(self, payment_entry_name):
		payment_entry = frappe.get_doc("Payment Entry", payment_entry_name)
		self._validate_payment_entry_mapping(payment_entry)
		if payment_entry.docstatus == 0:
			payment_entry.submit()
			self._validate_payment_entry_mapping(payment_entry)
		self._set_payment_entry_link(payment_entry.name)
		return payment_entry

	def _validate_payment_entry_mapping(self, payment_entry):
		precision = payment_entry.precision("paid_amount")
		if payment_entry.company != self.company:
			frappe.throw(
				_("Generated Payment Entry {0} does not match the payment request").format(
					frappe.bold(payment_entry.name)
				)
			)
		if payment_entry.party_type != "Supplier" or payment_entry.party != self.supplier:
			frappe.throw(
				_("Generated Payment Entry {0} does not match the payment request").format(
					frappe.bold(payment_entry.name)
				)
			)
		if flt(payment_entry.paid_amount, precision) != flt(self.amount, precision):
			frappe.throw(
				_("Generated Payment Entry {0} does not match the payment request").format(
					frappe.bold(payment_entry.name)
				)
			)
		if getdate(payment_entry.posting_date) != getdate(self.posting_date):
			frappe.throw(
				_("Generated Payment Entry {0} does not match the payment request").format(
					frappe.bold(payment_entry.name)
				)
			)
		if self.mode_of_payment and payment_entry.mode_of_payment != self.mode_of_payment:
			frappe.throw(
				_("Generated Payment Entry {0} does not match the payment request").format(
					frappe.bold(payment_entry.name)
				)
			)
		if payment_entry.docstatus == 2:
			frappe.throw(
				_("Generated Payment Entry {0} is cancelled; a duplicate will not be created").format(
					frappe.bold(payment_entry.name)
				)
			)

	def _set_payment_entry_link(self, payment_entry_name):
		self.payment_entry = payment_entry_name
		self.db_set("payment_entry", payment_entry_name, update_modified=False)

	def _resolve_company_quietly(self):
		try:
			return resolve_payment_company(self.supplier)
		except frappe.ValidationError:
			return None

	@staticmethod
	def _supplier_outstanding(supplier, company):
		rows = frappe.get_all(
			"Purchase Invoice",
			filters={
				"docstatus": 1,
				"supplier": supplier,
				"company": company,
				"outstanding_amount": (">", 0),
			},
			fields=["sum(outstanding_amount) as outstanding"],
		)
		return flt(rows[0].outstanding) if rows else 0

	@staticmethod
	def _qualifying_invoices(supplier, company):
		return frappe.get_all(
			"Purchase Invoice",
			filters={
				"docstatus": 1,
				"supplier": supplier,
				"company": company,
				"outstanding_amount": (">", 0),
			},
			fields=["name", "outstanding_amount", "posting_date"],
			order_by="posting_date asc, name asc",
		)

	def _allocate_fifo_references(self, payment_entry, invoices, amount):
		remaining = flt(amount)
		payment_entry.set("references", [])
		for invoice in invoices:
			if remaining <= 0:
				break
			outstanding = flt(invoice.outstanding_amount)
			if outstanding <= 0:
				continue
			allocated = min(remaining, outstanding)
			payment_entry.append(
				"references",
				{
					"reference_doctype": "Purchase Invoice",
					"reference_name": invoice.name,
					"outstanding_amount": outstanding,
					"allocated_amount": allocated,
				},
			)
			remaining -= allocated
		if remaining > 0:
			frappe.throw(_("Amount exceeds the total outstanding"))
		payment_entry.paid_amount = flt(amount)
		payment_entry.received_amount = flt(amount)
		payment_entry.reference_no = self.reference_no or None
		payment_entry.reference_date = self.reference_date or None
		if not payment_entry.get("custom_remarks"):
			# Native custom-remarks switch: keep the wrapper-context remarks
			# through ERPNext's own validate()/set_remarks() lifecycle.
			payment_entry.custom_remarks = 1
		remarks_parts = [f"Cardboard Supplier Payment {self.name}"]
		if self.notes:
			remarks_parts.append(self.notes)
		payment_entry.remarks = " - ".join(remarks_parts)
		return payment_entry

	def _generate_payment_entry(self, wrapper):
		"""Build the unsaved native Payment Entry for this wrapper (server-side).

		Uses ERPNext's standard get_payment_entry against the oldest outstanding
		Purchase Invoice, with the Cash/Bank account mapped by the Mode of Payment
		Account configuration. Only the unsaved draft is adjusted; ERPNext native
		validation remains authoritative for the submitted document.
		"""
		supplier = wrapper.supplier
		company = resolve_payment_company(supplier)
		wrapper.company = wrapper.company or company
		mode_of_payment = wrapper.mode_of_payment
		bank_account = get_mapped_payment_account(mode_of_payment, company)
		invoices = self._qualifying_invoices(supplier, company)
		if not invoices:
			frappe.throw(_("No outstanding invoices exist for this supplier"))
		total_outstanding = sum(flt(invoice.outstanding_amount) for invoice in invoices)
		amount = flt(wrapper.amount)
		if amount <= 0:
			frappe.throw(_("Amount must be greater than zero"))
		if amount > total_outstanding:
			frappe.throw(_("Amount exceeds the total outstanding"))

		from erpnext.accounts.doctype.payment_entry.payment_entry import get_payment_entry

		payment_entry = get_payment_entry(
			"Purchase Invoice",
			invoices[0].name,
			bank_account=bank_account,
			party_amount=amount,
		)
		payment_entry.posting_date = wrapper.posting_date or nowdate()
		payment_entry.mode_of_payment = mode_of_payment
		self._allocate_fifo_references(payment_entry, invoices, amount)
		return payment_entry


def resolve_payment_company(supplier=None):
	"""Resolve the payment company from the Cardboard Dashboard Settings config.

	The company is configuration-driven, never guessed from the supplier or from
	company defaults: it is the single company configured in the existing
	Cardboard Dashboard Settings single (the same source the dashboard uses).
	"""
	company = frappe.db.get_single_value("Cardboard Dashboard Settings", "company")
	if not company:
		frappe.throw(
			_("Configure Company in Cardboard Dashboard Settings before recording supplier payments"),
			frappe.ValidationError,
		)
	if not frappe.db.exists("Company", company):
		frappe.throw(
			_("Company {0} in Cardboard Dashboard Settings does not exist").format(
				frappe.bold(company)
			),
			frappe.ValidationError,
		)
	return company


def get_mapped_payment_account(mode_of_payment, company):
	"""Resolve the Cash/Bank account ERPNext maps for this Mode of Payment.

	Sourced from ERPNext's native Mode of Payment Account configuration through
	erpnext.accounts.doctype.sales_invoice.sales_invoice.get_bank_cash_account -
	the same source get_payment_entry uses internally. Nothing is hardcoded.
	"""
	from erpnext.accounts.doctype.sales_invoice.sales_invoice import get_bank_cash_account

	if not frappe.db.exists("Mode of Payment", mode_of_payment):
		frappe.throw(
			_("No enabled Mode of Payment Account is mapped for {0} in company {1}").format(
				frappe.bold(mode_of_payment), frappe.bold(company)
			),
			frappe.ValidationError,
		)
	try:
		account = get_bank_cash_account(mode_of_payment, company).get("account")
	except frappe.ValidationError:
		frappe.clear_last_message()
		account = None
	if not account:
		frappe.throw(
			_("No enabled Mode of Payment Account is mapped for {0} in company {1}").format(
				frappe.bold(mode_of_payment), frappe.bold(company)
			),
			frappe.ValidationError,
		)
	row = frappe.db.get_value(
		"Account",
		account,
		["company", "account_type", "is_group", "disabled", "account_currency"],
		as_dict=True,
	)
	company_currency = frappe.get_cached_value("Company", company, "default_currency")
	if (
		not row
		or row.company != company
		or row.disabled
		or row.is_group
		or row.account_type not in ("Cash", "Bank")
	):
		frappe.throw(
			_("No enabled Mode of Payment Account is mapped for {0} in company {1}").format(
				frappe.bold(mode_of_payment), frappe.bold(company)
			),
			frappe.ValidationError,
		)
	if row.account_currency != company_currency:
		frappe.throw(
			_("No enabled Mode of Payment Account is mapped for {0} in company {1}").format(
				frappe.bold(mode_of_payment), frappe.bold(company)
			),
			frappe.ValidationError,
		)
	return account


@frappe.whitelist()
def get_supplier_payment_context(supplier=None):
	"""Return the company/outstanding context the form JS needs for the headline."""
	if not supplier:
		frappe.throw(_("Supplier is required"))
	company = None
	outstanding = None
	try:
		company = resolve_payment_company(supplier)
		outstanding = CardboardSupplierPayment._supplier_outstanding(supplier, company)
	except frappe.ValidationError:
		frappe.clear_last_message()
	return {"company": company, "outstanding": outstanding}
