import frappe
from frappe import _
from frappe.model.document import Document
from frappe.utils import flt, getdate, nowdate
from frappe.utils.nestedset import get_descendants_of


class CardboardSale(Document):
	# Operational outbound sale. The stock effect lives entirely in one native
	# ERPNext Material Issue Stock Entry generated by ERPNext's own utility; this
	# wrapper never writes Bin rows, Stock Ledger Entries, receivables, revenue
	# GL, or selling invoices. ERPNext stock stays the only balance authority and
	# the sale amount is informational, not posted accounting revenue.
	INSUFFICIENT_STOCK_MESSAGE = "الكمية المتاحة من هذا النوع لا تكفي لإتمام عملية البيع."

	def validate(self):
		self.validate_posting_date()
		self.validate_settings()
		self.validate_item()
		self.validate_quantity()
		self.calculate_total_amount()

	def validate_posting_date(self):
		self.posting_date = self.posting_date or nowdate()
		if getdate(self.posting_date) > getdate(nowdate()):
			frappe.throw(_("Posting Date cannot be in the future"))

	def validate_settings(self):
		settings = frappe.get_cached_doc("Cardboard Dashboard Settings")
		if not settings.company or not frappe.db.exists("Company", settings.company):
			frappe.throw(_("Configure Company in Cardboard Dashboard Settings before recording sales"))
		if not settings.cardboard_item_group or not frappe.db.exists(
			"Item Group", settings.cardboard_item_group
		):
			frappe.throw(_("Configure Cardboard Item Group in Cardboard Dashboard Settings before recording sales"))
		if not settings.default_warehouse:
			frappe.throw(_("لم يتم تحديد المخزن الافتراضي في إعدادات إدارة الكرتون."))
		if self.company and self.company != settings.company:
			frappe.throw(_("Cardboard Sale company must match the configured Company"))
		if self.warehouse and self.warehouse != settings.default_warehouse:
			frappe.throw(_("Cardboard Sale must use the configured default warehouse"))
		self.company = settings.company
		self.warehouse = settings.default_warehouse
		warehouse = frappe.db.get_value(
			"Warehouse", self.warehouse, ["name", "company", "disabled", "is_group"], as_dict=True
		)
		if not warehouse or warehouse.disabled or warehouse.is_group or warehouse.company != settings.company:
			frappe.throw(_("المخزن الافتراضي في إعدادات إدارة الكرتون غير صالح."))

	def validate_item(self):
		settings = frappe.get_cached_doc("Cardboard Dashboard Settings")
		item_groups = [
			settings.cardboard_item_group,
			*get_descendants_of("Item Group", settings.cardboard_item_group),
		]
		item = frappe.db.get_value(
			"Item",
			self.item,
			["name", "disabled", "is_stock_item", "item_group", "stock_uom"],
			as_dict=True,
		)
		if not item or item.disabled or not item.is_stock_item:
			frappe.throw(_("Select a valid cardboard item"))
		if item.stock_uom != "Kg":
			frappe.throw(_("Item Stock UOM must be Kg"))
		if item.item_group not in item_groups:
			frappe.throw(_("Select an item from the configured Cardboard Item Group"))

	def validate_quantity(self):
		if flt(self.quantity) <= 0:
			frappe.throw(_("Quantity must be greater than zero"))
		if flt(self.rate_per_kg) < 0:
			frappe.throw(_("Rate per Kg cannot be negative"))

	def calculate_total_amount(self):
		self.total_amount = flt(
			flt(self.quantity) * flt(self.rate_per_kg), self.precision("total_amount")
		)

	def validate_available_stock(self):
		from erpnext.stock.utils import get_stock_balance

		available = get_stock_balance(self.item, self.warehouse, self.posting_date)
		if flt(available) < flt(self.quantity):
			frappe.throw(_(self.INSUFFICIENT_STOCK_MESSAGE))

	def on_submit(self):
		self.validate_available_stock()
		self._lock_for_integration()
		existing_name = self._existing_stock_entry_name()
		if existing_name:
			self._complete_existing_stock_entry(existing_name)
		else:
			from erpnext.stock.doctype.stock_entry.stock_entry_utils import make_stock_entry

			stock_entry = make_stock_entry(
				item_code=self.item,
				qty=flt(self.quantity),
				company=self.company,
				from_warehouse=self.warehouse,
				purpose="Material Issue",
				posting_date=self.posting_date,
				do_not_submit=False,
			)
			self._validate_stock_entry_mapping(stock_entry)
			self._set_stock_entry_link(stock_entry.name)

	def before_cancel(self):
		# The wrapper's forward link to its native Stock Entry is intentional:
		# the stock entry cancels first while this document keeps its link.
		self.ignore_linked_doctypes = ("Stock Entry",)
		self.cancel_stock_entry()

	def cancel_stock_entry(self):
		linked_name = self.stock_entry or frappe.db.get_value(
			"Cardboard Sale", self.name, "stock_entry"
		)
		if not linked_name:
			frappe.throw(_("Cardboard Sale {0} has no linked Stock Entry").format(frappe.bold(self.name)))
		stock_entry = frappe.get_doc("Stock Entry", linked_name)
		if stock_entry.docstatus == 2:
			return
		self._validate_stock_entry_mapping(stock_entry)
		if stock_entry.docstatus == 0:
			frappe.throw(_("Generated Stock Entry {0} must be submitted before cancelling").format(frappe.bold(linked_name)))
		stock_entry.flags.ignore_links = True
		stock_entry.cancel()

	def _lock_for_integration(self):
		# Serialize generation per wrapper so concurrent submissions cannot
		# create duplicate Stock Entries (Cardboard Supplier Payment precedent).
		frappe.db.sql(
			"select name from `tabCardboard Sale` where name = %s for update",
			(self.name,),
		)
		self.stock_entry = frappe.db.get_value("Cardboard Sale", self.name, "stock_entry")

	def _existing_stock_entry_name(self):
		return self.stock_entry or frappe.db.get_value("Cardboard Sale", self.name, "stock_entry")

	def _complete_existing_stock_entry(self, stock_entry_name):
		stock_entry = frappe.get_doc("Stock Entry", stock_entry_name)
		self._validate_stock_entry_mapping(stock_entry)
		if stock_entry.docstatus == 0:
			stock_entry.submit()
			self._validate_stock_entry_mapping(stock_entry)
		self._set_stock_entry_link(stock_entry.name)
		return stock_entry

	def _validate_stock_entry_mapping(self, stock_entry):
		precision = stock_entry.precision("transfer_qty")
		items = stock_entry.items or []
		if (
			stock_entry.company != self.company
			or stock_entry.purpose != "Material Issue"
			or len(items) != 1
			or items[0].item_code != self.item
			or items[0].s_warehouse != self.warehouse
			or flt(items[0].transfer_qty, precision) != flt(self.quantity, precision)
			or getdate(stock_entry.posting_date) != getdate(self.posting_date)
		):
			frappe.throw(_("Generated Stock Entry {0} does not match the sale").format(frappe.bold(stock_entry.name)))
		if stock_entry.docstatus == 2:
			frappe.throw(_("Generated Stock Entry {0} is cancelled; a duplicate will not be created").format(frappe.bold(stock_entry.name)))

	def _set_stock_entry_link(self, stock_entry_name):
		self.stock_entry = stock_entry_name
		self.db_set("stock_entry", stock_entry_name, update_modified=False)
